apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-09
data:
  URL: google.com
  FQDN: www.google.com

---
kind: Pod
apiVersion: v1
metadata:
  name: debug-01
spec:
  containers:
    - name: debug
      image: rkalluru/debug
      env:
        name: URL
        value: yahoo.com